# Generated by Django 4.2.4 on 2023-08-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescore",
            name="game",
            field=models.TextField(
                choices=[("MATH", "Math Game"), ("ANAGRAM", "Anagram Game")],
                default="MATH",
            ),
        ),
    ]
